version: '3.6'
services:
  mosquitto:
    #image: eclipse-mosquitto:2.0.15
    build: ./mitstack/mosquitto
    container_name: mosquitto
    restart: always
    env_file: .env
    volumes:
      - ./mitstack/mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mitstack/mosquitto/conf/passwordfile.txt:/mosquitto/config/passwordfile.txt
      - ./mitstack/mosquitto/data/:/mosquitto/data/
      - ./mitstack/mosquitto/log/:/mosquitto/log/
    ports:
      - 1883:1883

  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=bmetk 
      - DOCKER_INFLUXDB_INIT_BUCKET=opendaq 
      - DOCKER_INFLUXDB_INIT_RETENTION=7d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=6f9bcc542b6fb949ddd4354beea4a4ca75645531cf6f409469bb3bcd11fee168
    volumes:
      - ./mitstack/influxdb_storage:/var/lib/influxdb2:rw
    ports:
      - 8086:8086

  #telegraf:
  #  image: telegraf:1.26-alpine
  #  container_name: telegraf
  #  restart: always
  #  volumes:
  #    - ./mitstack/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #  env_file: .env
  #  depends_on:
  #    - influxdb
  #    - mosquitto
  #  ports:
  #   - 8125:8125

  analytics_backend:
    build: ./analytics_backend
    container_name: analytics_backend
    env_file: .env
    restart: always
    depends_on:
      - mosquitto
    ports:
      - 8765:8765
      #- 8766:8766

  frontend:
    build: ./dashboard/frontend
    container_name: frontend
    restart: always
    depends_on:
      - analytics_backend
    ports:
      - 8050:8050

  download:
    build: ./dashboard/download
    container_name: download
    restart: always
    env_file: .env
    depends_on:
      - frontend
      - influxdb
    ports:
      - 5000:5000